sudo: required
services:
  - docker

before_install:
  - docker build -t jcorrea/docker-react -f Dockerfile_dev .

#script:
#  - docker run jcorrea/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket:
    name: "elasticbeanstalk-us-east-2-817494826592"
    path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
